# 配置tomcat端口号
server:
  port: 80

# spring boot spring-boot-autoconfigure spring.factories
# RedisAutoConfiguration
spring:
  redis:
    host: 127.0.0.1
    port: 6379
#spring.redis.lettuce.pool.max-active=8
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/java-notes?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

  kafka:
    bootstrap-servers: 192.168.10.133:9092
    consumer:
      group-id: 0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nuc.meerkatx.springbootstudy.pojo